version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: broomin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: broomin_db
      MYSQL_USER: broomin_user
      MYSQL_PASSWORD: broomin_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/db/initdb.d:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
      
  backend:
    container_name: broomin-backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=broomin_user
      - DB_PASSWORD=broomin_password
      - DB_NAME=broomin_db
      - DB_PORT=3306
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "node", "-e", "require('axios').get('http://localhost:5000/health').catch(() => process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: broomin-frontend
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - backend
    stdin_open: true
    tty: true
    command: sh -c "npm run dev -- --host"  # Add --host flag to expose the dev server

volumes:
  mysql_data:
